#
# PX4 NuttX development environment
#

FROM px4io/px4-dev-base
MAINTAINER Daniel Agar <daniel@agar.ca>

RUN apt-get update \
	&& apt-get -y --quiet --no-install-recommends install \
		autoconf \
		automake \
		bison \
		build-essential \
		file \
		flex \
		genromfs \
		gperf \
		libncurses-dev \
		libtool \
		pkg-config \
	&& apt-get -y autoremove \
	&& apt-get clean autoclean \
	# gcc-arm-embedded 6-2017-q2-update (https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads)
	&& mkdir -p /opt/gcc && cd /opt/gcc \
	&& wget -qO- "https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/6-2017q2/gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2" | tar jx --strip 1 \
	&& rm -rf /opt/gcc/share/doc \
	# manual ccache setup for arm-none-eabi-g++/arm-none-eabi-gcc
	&& ln -s /usr/bin/ccache /usr/lib/ccache/arm-none-eabi-g++ \
	&& ln -s /usr/bin/ccache /usr/lib/ccache/arm-none-eabi-gcc \
	# nuttx tools
	&& git clone --depth 1 https://bitbucket.org/nuttx/tools.git /tmp/tools \
	&& cd /tmp/tools/kconfig-frontends \
	&& autoreconf -f -i \
	&& ./configure --enable-mconf --disable-nconf --disable-gconf --disable-qconf -prefix=/usr && make && make install \
	# cleanup
	&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

ENV PATH "$PATH:/opt/gcc/bin"
